dist: trusty

language: cpp

compiler:
 - gcc

before_install:
 - git clone http://github.com/FantasticOnAStick/foas_common.git
 - git clone http://github.com/FantasticOnAStick/foas_message.git
 - git clone http://github.com/FantasticOnAStick/foas_plugin.git
 - git clone http://github.com/FantasticOnAStick/foas_node.git
 - git clone http://github.com/FantasticOnAStick/plugins.git

script:
 - cd foas_node
 - mkdir build
 - cd build
 - cmake ..
 - make
